### ISSUE TITLE
after select the phone number getting traceback 

### ISSUE THREAD

**Issue by baramhs** [clausemaven/Maven-Telegram-AIO-Scrapper-and-Adder#1]
Selected API ID: 13680000
Traceback (most recent call last):
  File "C:\Users\TomG\Desktop\Maven-Telegram-AIO-Scrapper-and-Adder-main\Maven.py", line 104, in <module>
    client = TelegramClient(f"../sessions/{phone}", api_id, api_hash)
  File "C:\Users\TomG\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 273, in __init__
    session = SQLiteSession(session)
  File "C:\Users\TomG\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
  File "C:\Users\TomG\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sessions\sqlite.py", line 228, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file

**Comment by clausemaven** [comment]
> sqlite3.OperationalError: unable to open database file
This was because I didn't add a sessions folder, this is now fixed. To fix it, redownload and you should be good to go. Sorry for the inconvinence :)
